//URL
const URL = 'https://thingproxy.freeboard.io/fetch/http://164.90.216.97';

// Products
const ALL_PRODUCTS = 'ALL_PRODUCTS';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_PRODUCTS_IN_CATEGORY = 'GET_PRODUCTS_IN_CATEGORY';
const CLEAR_PRODUCTS_IN_CATEGORY = 'CLEAR_PRODUCTS_IN_CATEGORY';
const GET_COUNT_PRODUCTS_IN_CATEGORY = 'GET_COUNT_PRODUCTS_IN_CATEGORY';
const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS';
const GET_PRODUCT = 'GET_PRODUCT';
const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

// USER
const USER_AUTH = 'USER_AUTH';
const USER_REGISTER = 'USER_REGISTER';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

export {
   ALL_PRODUCTS,
   GET_ALL_CATEGORIES,
   GET_PRODUCTS_IN_CATEGORY,
   CLEAR_PRODUCTS_IN_CATEGORY,
   GET_COUNT_PRODUCTS_IN_CATEGORY,
   GET_SEARCH_PRODUCTS,
   USER_AUTH,
   USER_REGISTER,
   USER_LOGIN,
   USER_LOGOUT,
   GET_PRODUCT,
   CLEAR_PRODUCT,
   URL
}