//URL

// const CORS = 'https://cors-anywhere.herokuapp.com/';

//https://cors-anywhere.herokuapp.com/

const URL = `https://www.smartapi.uz`;

// Products
const ALL_PRODUCTS = 'ALL_PRODUCTS';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_PRODUCTS_IN_CATEGORY = 'GET_PRODUCTS_IN_CATEGORY';
const CLEAR_PRODUCTS_IN_CATEGORY = 'CLEAR_PRODUCTS_IN_CATEGORY';
const GET_COUNT_PRODUCTS_IN_CATEGORY = 'GET_COUNT_PRODUCTS_IN_CATEGORY';
const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS';
const GET_PRODUCT = 'GET_PRODUCT';
const CLEAR_PRODUCT = 'CLEAR_PRODUCT';


// Cart
const ADD_TO_CART_START = 'ADD_TO_CART_START';
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
const CLEAR_CART = 'CLEAR_CART';
const DELETE_FROM_CART_SUCCESS = 'DELETE_FROM_CART_SUCCESS';
const DELETE_FROM_CART_START = 'DELETE_FROM_CART_START';
// const REMOVE_ALL = 'REMOVE_ALL';
const GET_CART = 'GET_CART';
// const COUNT_ALL_IN_CART = 'COUNT_ALL_IN_CART';
// const COUNT_PRODUCT_IN_CART = 'COUNT_PRODUCT_IN_CART';

// User
const USER_AUTH = 'USER_AUTH';
const USER_REGISTER = 'USER_REGISTER';
const CLEAR_USER_REGISTER = 'CLEAR_USER_REGISTER';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

// Checkout
const CONFIRM_ORDER = 'CONFIRM_ORDER';
const FETCH_ORDER = 'FETCH_ORDER';
const FETCH_ORDER_ALL = 'FETCH_ORDER_ALL';

export {
   ALL_PRODUCTS,
   GET_ALL_CATEGORIES,
   GET_PRODUCTS_IN_CATEGORY,
   CLEAR_PRODUCTS_IN_CATEGORY,
   GET_COUNT_PRODUCTS_IN_CATEGORY,
   GET_SEARCH_PRODUCTS,
   CLEAR_PRODUCT,

   USER_AUTH,
   USER_REGISTER,
   CLEAR_USER_REGISTER,
   USER_LOGIN,
   USER_LOGOUT,
   GET_PRODUCT,

   ADD_TO_CART_START,
   ADD_TO_CART_SUCCESS,
   REMOVE_FROM_CART_START,
   REMOVE_FROM_CART_SUCCESS,
   GET_CART,
   CLEAR_CART,
   DELETE_FROM_CART_SUCCESS,
   DELETE_FROM_CART_START,

   FETCH_ORDER,
   CONFIRM_ORDER,
   FETCH_ORDER_ALL,

   URL
}